# .goreleaser.yml for binnit project
before:
  hooks:
    - make clean
    - go mod download
builds:
  - env:
    - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.BuildTime={{.Date}}
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm64
archive:
  replacements:
    386: i386
  files:
    - LICENSE.md
    - README.md
    - tpl/*
    - static/*
    - log
    - paste
    - conf/binnit.cfg
  wrap_in_directory: binnit
dockers:
  -
    goos:
      linux
    goarch:
      amd64
    image_templates:
      - "karasz/binnit:latest"
      - "karasz/binnit:{{ .Tag }}"
    skip_push: true
    dockerfile: Dockerfile
    extra_files:
      - conf/
      - static/
      - tpl/
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
sign:
  artifacts: checksum
