# .goreleaser.yml for binnit project
before:
  hooks:
    - make clean
builds:
  - env:
    - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.Version={{.VERSION}} -X main.BuildTime={{.Date}}
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm64
archive:
  replacements:
    linux: Linux
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
sign:
  artifacts: checksum
